### ISSUE TITLE
advanced lane lines master problems

### ISSUE THREAD

**Issue by oussa055** [andersy005/self-driving-car-nd#2]
Hey anderson , 
 I faced this error when i try to use my own video or image in your "advanced lane lines project " : 
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
i  wanna change the dst and scr to adabted my project like you do in this video https://www.youtube.com/watch?v=3NnTZ9NR03k but i can't find solution ( i don't know the part that i can change to sucess my project)
i really need your help 
thanks

**Comment by andersy005** [comment]
@oussa055, Thank you for opening this issue! Unfortunately, I am very swamped with work right now. How about I get back to you  some time over the weekend?

**Comment by oussa055** [comment]
ok i will wait you this weekend

**Comment by oussa055** [comment]
i m still waitin bro , if u can help me please i really need your help

**Comment by oussa055** [comment]
i m still waitin bro , if u can help me please i really need your help i don't have much time so if you can't help just tell me

**Comment by andersy005** [comment]
@oussa055, 
1) To make sure that your input is not the problem, can you try to use a different video input and see if you encounter the same error?

2) Can you post the  **full** traceback of the error you are getting instead of the `TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'` so that I know which lines are failing?

**Comment by oussa055** [comment]
runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Video input file: vido_.mp4 does not exist.  Please check and try again.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1




runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Video input file: vido_.mp4 does not exist.  Please check and try again.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1




runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Video input file: vido_.mp4 does not exist.  Please check and try again.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1




runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Video input file: vido-.mp4 does not exist.  Please check and try again.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1




runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Camera Calibration data restored from camera_cal/calibrationdata.p
video processing test_vid.mp4...
Traceback (most recent call last):

  File "<ipython-input-7-711172d6f3c7>", line 1, in <module>
    runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 167, in <module>
    video_clip = clip1.fl_image(process_image)

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 511, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 138, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "<D:\Anaconda3\lib\site-packages\decorator.py:decorator-gen-185>", line 2, in set_make_frame

  File "D:\Anaconda3\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 666, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]

  File "<D:\Anaconda3\lib\site-packages\decorator.py:decorator-gen-138>", line 2, in get_frame

  File "D:\Anaconda3\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 95, in get_frame
    return self.make_frame(t)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 138, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 511, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 78, in process_image
    result = process_road_image(image, roadMgr, diagMgr, scrType=scrType, debug=debug)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 43, in process_road_image
    roadMgr.findLanes(img)

  File "C:\Users\MBM info\Documents\GitHub\SDC-P4\p4lib\roadManager.py", line 161, in findLanes
    self.roadHorizonGap =( self.projMgr.curGradient - self.curImgFtr.roadhorizon)

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by oussa055** [comment]
runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')
Reloaded modules: p4lib, p4lib.cameraCal, p4lib.imageFilters, p4lib.projectionManager, p4lib.line, p4lib.roadManager, p4lib.diagManager
Camera Calibration data restored from camera_cal/calibrationdata.p
video processing test_vid.mp4...
Traceback (most recent call last):

  File "<ipython-input-7-711172d6f3c7>", line 1, in <module>
    runfile('C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py', wdir='C:/Users/MBM info/Documents/GitHub/SDC-P4')

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 167, in <module>
    video_clip = clip1.fl_image(process_image)

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 511, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 138, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "<D:\Anaconda3\lib\site-packages\decorator.py:decorator-gen-185>", line 2, in set_make_frame

  File "D:\Anaconda3\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 666, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]

  File "<D:\Anaconda3\lib\site-packages\decorator.py:decorator-gen-138>", line 2, in get_frame

  File "D:\Anaconda3\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 95, in get_frame
    return self.make_frame(t)

  File "D:\Anaconda3\lib\site-packages\moviepy\Clip.py", line 138, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "D:\Anaconda3\lib\site-packages\moviepy\video\VideoClip.py", line 511, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 78, in process_image
    result = process_road_image(image, roadMgr, diagMgr, scrType=scrType, debug=debug)

  File "C:/Users/MBM info/Documents/GitHub/SDC-P4/P4pipeline.py", line 43, in process_road_image
    roadMgr.findLanes(img)

  File "C:\Users\MBM info\Documents\GitHub\SDC-P4\p4lib\roadManager.py", line 161, in findLanes
    self.roadHorizonGap =( self.projMgr.curGradient - self.curImgFtr.roadhorizon)

TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

**Comment by andersy005** [comment]
It appears that at one point when the algorithm tries to compute the road horizon gap, your `projMgr.curGradient` is None, as a result, it is unable to perform `self.projMgr.curGradient - self.curImgFtr.roadhorizon`. Coming up with a robust solution for this issue is not a trivial task, and to be honest I don't have enough free time cycles to debug this for all use-cases. Therefore, my suggestion to you would be to add a check right before `self.roadHorizonGap =( self.projMgr.curGradient - self.curImgFtr.roadhorizon)` to make sure that `self.projMgr.curGradient` is not `None`:

```python
if self.projMgr.curGradient:
    self.roadHorizonGap =( self.projMgr.curGradient - self.curImgFtr.roadhorizon)
else:
    self.roadHorizonGap =( 0.0 - self.curImgFtr.roadhorizon)
```

P.S: I am not sure about the implications/effects of this change ( I haven't tested it) but it believe that it would the first step in the right direction. Let me know how it goes.

**Comment by oussa055** [comment]
new issue appear when i try to use your solution :

  File "C:\Users\MBM info\Documents\GitHub\SDC-P4\p4lib\roadManager.py", line 184, in findLanes
    self.leftLane.radius_in_meters(distance)

  File "C:\Users\MBM info\Documents\GitHub\SDC-P4\p4lib\line.py", line 271, in radius_in_meters
    if len(self.allY) > 0 and len(self.currentX) > 0 or len(self.allY) == len(self.currentX):

TypeError: object of type 'NoneType' has no len()

**Comment by andersy005** [comment]
@oussa055, unfortunately, I don't have free time to look into this in the next 5 days. And as I mentioned before, it would take time to come up with a robust fix that addresses the issues you raised. For a robust fix, I would need to have some unit tests in place that tests all assumptions made throughout the code base. Therefore, I am sorry I won't be able to come up with a fix for this issue in a timely manner. If you come up with a solution, please let me know.
